version: "3"

services:
  1st-server:
    image: nginx
    container_name: "1st-container"
    volumes:
      - ./1st-server:/usr/share/nginx/html
    ports:
      - 7000:80

  2nd-server:
    image: nginx
    container_name: "2nd-container"
    volumes:
      - ./2nd-server:/usr/share/nginx/html
    ports:
      - 7001:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
